version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: money_plan
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - money_plan_network

  backend:
    build: ./services/backend/
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=mongodb://admin:password123@mongo:27017/money_plan?authSource=admin
    volumes:
      - './services/backend:/app'
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - money_plan_network

networks:
    money_plan_network:

volumes:
  mongo:
